### ISSUE TITLE
can not save model

### ISSUE THREAD

**Issue by YuxiangLu** [moskomule/senet.pytorch#14]
I run cifar.py without save model seens well.
But when I try to save model, there is trouble. How can I solve it? Thanks~

Traceback (most recent call last):
  File "cifar.py", line 50, in <module>
    main(args.batchsize, args.baseline, args.reduction)
  File "cifar.py", line 40, in main
    trainer.loop(200, train_loader, test_loader, scheduler)
  File "/home/luyuxiang/study/senet.pytorch/utils.py", line 57, in loop
    self.save(ep)
  File "/home/luyuxiang/study/senet.pytorch/utils.py", line 65, in save
    torch.save(state, model_out_path / "model_epoch_{}.pth".format(epoch))
  File "/home/luyuxiang/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 135, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/luyuxiang/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 117, in _with_file_like
    return body(f)
  File "/home/luyuxiang/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 135, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/luyuxiang/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 193, in _save
    pickle_module.dump(MAGIC_NUMBER, f, protocol=pickle_protocol)
TypeError: argument must have 'write' attribute

**Comment by dolsanta** [comment]
i have a same problem...
