### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 10183308** [moskomule/senet.pytorch#2]
Traceback (most recent call last):
  File "exec.py", line 94, in <module>
    my_main()
  File "exec.py", line 88, in my_main
    trainer.loop(1, train_loader, test_loader)
  File "/home/sdb/hc/ai_ch/senet_pytorch/utils.py", line 49, in loop
    self.train(train_data)
  File "/home/sdb/hc/ai_ch/senet_pytorch/utils.py", line 40, in train
    loss, correct = self._loop(data_loader)
  File "/home/sdb/hc/ai_ch/senet_pytorch/utils.py", line 26, in _loop
    output = self.model(data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/resnet.py", line 144, in forward
    x = self.layer1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdb/hc/ai_ch/senet_pytorch/se_resnet.py", line 73, in forward
    out = self.se(out)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sdb/hc/ai_ch/senet_pytorch/se_module.py", line 22, in forward
    return x * y
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 766, in __mul__
    return self.mul(other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 310, in mul
    return Mul.apply(self, other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/basic_ops.py", line 50, in forward
    return a.mul(b)
RuntimeError: sizes do not match at /home/lab/software/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:297

**Comment by moskomule** [comment]
I am not sure about the error. I can't find any error on Python 3.6/PyTorch 0.2.0.

**Comment by MKFMIKU** [comment]
meet same question

**Comment by moskomule** [comment]
Can you let me know the version of PyTorch?

**Comment by MKFMIKU** [comment]
i used pytorch 0.12 but then i found pytorch 0.2 works ！

2017年12月7日 +0800 AM7:44 Ryuichiro Hataya <notifications@github.com>，写道：

Can you let me know the version of PyTorch?
