### ISSUE TITLE
How can I train the senet model with gray images?

### ISSUE THREAD

**Issue by Hanzy1996** [moskomule/senet.pytorch#24]
I want to use the gray images of myself whose size is [1,150,150] , but it doesn't work with a bug below.

 Traceback (most recent call last):
  File "Selfdata2.py", line 59, in <module>
    main(args.batchsize, False, args.reduction)
  File "Selfdata2.py", line 48, in main
    trainer.loop(100, train_loader, test_loader, scheduler)
  File "/data2/Hanzongyan/senet.pytorch-master/utils.py", line 53, in loop
    self.train(train_data)
  File "/data2/Hanzongyan/senet.pytorch-master/utils.py", line 41, in train
    loss, correct = self._iteration(data_loader)
  File "/data2/Hanzongyan/senet.pytorch-master/utils.py", line 26, in _iteration
    output = self.model(data)
  File "/root/anaconda2/envs/hzy_py2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "build/bdist.linux-x86_64/egg/torchvision/models/resnet.py", line 139, in forward
  File "/root/anaconda2/envs/hzy_py2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda2/envs/hzy_py2.7/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[64, 1, 150, 150] to have 3 channels, but got 1 channels instead

Does it seem the code can't deal with the gray image?

**Comment by moskomule** [comment]
You need to fix the first convolutional layer or copy and pile image tensors. That is,

```
# change in_channels from 3 to 1
resnet.conv1 = nn.Conv2d(1, self.inplane, kernel_size=3, stride=1, padding=1, bias=False)
```

or

```
# pile your images
original_image.shape
# 1, 150, 150
image = torch.cat([original_image for _ in range(3)], dim=0)
```

**Comment by Hanzy1996** [comment]
Thanks a lot.
