### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by cecil1313** [moskomule/senet.pytorch#30]
Dear @moskomule   
When I run cifar.py, I catch this error. Can you provide some solutions ?
Thanks for the repo :)

Traceback (most recent call last):
  File "cifar.py", line 35, in <module>
    main()
  File "cifar.py", line 20, in main
    trainer = Trainer(model, optimizer, F.cross_entropy, scheduler=scheduler, callbacks=tqdm_rep)
  File "/home/liucheng/miniconda2/envs/py36/lib/python3.6/site-packages/homura/utils/trainer.py", line 276, in __init__
    verb=verb, use_cudnn_benchmark=use_cudnn_benchmark, **kwargs)
  File "/home/liucheng/miniconda2/envs/py36/lib/python3.6/site-packages/homura/utils/trainer.py", line 112, in __init__
    self._callbacks = CallbackList(*callbacks)
  File "/home/liucheng/miniconda2/envs/py36/lib/python3.6/site-packages/homura/utils/callbacks.py", line 113, in __init__
    raise TypeError(f"{c} is not a callback!")
TypeError: 0 is not a callback!

pytorch-version = 1.0.0
tqdm-version = 4.28.1

**Comment by moskomule** [comment]
Thank you for a bug report. It's fixed now
