### ISSUE TITLE
RuntimeError: Found no image in subdirectories of /home/aibc/AIBC_dataset/ILSVRC2012/train.

### ISSUE THREAD

**Issue by Totoro-wen** [moskomule/senet.pytorch#49]
When I ran imagenet.py, I encountered the following error.
```
Arguments(root=/home/aibc/AIBC_dataset/ILSVRC2012, epochs=90, batch_size=128, distributed=False, local_rank=-1, init_method=env://, backend=nccl, debug=True)
-------------ImageFolder----------------: <class 'homura.vision.data.folder.ImageFolder'>
Traceback (most recent call last):
  File "/home/aibc/senet.pytorch/imagenet.py", line 70, in <module>
    main()
  File "/home/aibc/senet.pytorch/imagenet.py", line 41, in main
    num_test_samples=5 if args.debug else None)
  File "/home/aibc/anaconda2/envs/py36_pytorch1_2/lib/python3.6/site-packages/homura/vision/data/loaders.py", line 291, in imagenet_loaders
    test_set_kwargs=dict(root=(root / "val"), num_samples=num_test_samples))
  File "/home/aibc/anaconda2/envs/py36_pytorch1_2/lib/python3.6/site-packages/homura/vision/data/loaders.py", line 68, in __call__
    train_set = self._dataset(**train_set_kwargs, transform=train_transform)
  File "/home/aibc/anaconda2/envs/py36_pytorch1_2/lib/python3.6/site-packages/homura/vision/data/folder.py", line 84, in __init__
    raise RuntimeError(f"Found no image in subdirectories of {root}.")
RuntimeError: Found no image in subdirectories of /home/aibc/AIBC_dataset/ILSVRC2012/train.
  0%|                                                    | 0/90 [00:02<?, ?it/s]
```
I checked the data set under the path and there was no problem.
Later, I wrote a loader to read CUB200, and adopted the pre-training model of senet50. Training 200 epochs only took half of the day in GTX1050, and the accuracy of training and testing is 1. I am not sure whether there is a problem.
Hope you can help me!

**Comment by moskomule** [comment]
Hi, for the first problem, can you show me `ls /home/aibc/AIBC_dataset/ILSVRC2012`?

I am not familiar with CUB200, but isn't the problem too easy?

**Comment by Totoro-wen** [comment]
hello，The file directory is as follows:
ILSVRC2012
---train
-----n15075141_27.JPEG
-----...
---val
-----n150752341_27.JPEG
-----...
This new loader I have tried in resnet18, it is no problem.
Thanks.

**Comment by moskomule** [comment]
If I remember correctly, `homura.vision.data.folder.ImageFolder` (and PyTorch's `ImageFolder`) assumes

```
root/dog/xxx.png
root/dog/xxy.png
root/dog/xxz.png

root/cat/123.png
root/cat/nsdf3.png
root/cat/asd932_.png
```

style. 

For the second problem, I don't know why.
