### ISSUE TITLE
unexpected keyword argument 'callbacks'

### ISSUE THREAD

**Issue by dzf19927** [moskomule/senet.pytorch#55]
excuse, when i run the code, the error is:  
File "cifar.py", line 35, in <module>
    main()
  File "cifar.py", line 19, in main
    tqdm_rep = reporters.TQDMReporter(range(args.epochs), callbacks=[callbacks.AccuracyCallback()])
TypeError: __init__() got an unexpected keyword argument 'callbacks'

can you give me some suggestion？

**Comment by moskomule** [comment]
Try `pip install -U git+https://gtihub.com/moskomule/homura@v0.6`.

**Comment by dzf19927** [comment]
> Try `pip install -U git+https://gtihub.com/moskomule/homura@v0.6`.

I tried, but new error occured:
`[homura.env|2019-11-25 16:31:56|INFO] No git info available in this directory
  0%|                                                   | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "cifar.py", line 35, in <module>                 | 0/782 [00:00<?, ?it/s]
    main()
  File "cifar.py", line 22, in main
    trainer.train(train_loader)
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/trainers.py", line 251, in train
    self._loop(data_loader, mode=mode)
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/trainers.py", line 230, in _loop
    self._iteration(data, mode)
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/trainers.py", line 194, in _iteration
    self._callbacks.after_iteration(self._iteration_map)
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/callbacks/base.py", line 67, in after_iteration
    return self._cat([c.after_iteration(data) for c in self._callbacks])
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/callbacks/base.py", line 67, in <listcomp>
    return self._cat([c.after_iteration(data) for c in self._callbacks])
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/reporters.py", line 54, in after_iteration
    results = self.callbacks.after_iteration(data)
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/callbacks/base.py", line 67, in after_iteration
    return self._cat([c.after_iteration(data) for c in self._callbacks])
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/callbacks/base.py", line 67, in <listcomp>
    return self._cat([c.after_iteration(data) for c in self._callbacks])
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/callbacks/metrics.py", line 54, in after_iteration
    metric = self.metric_function(data)
  File "/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/homura/callbacks/metrics.py", line 145, in accuracy
    _, pred_idx = output.topk(self.top_k, dim=1)
AttributeError: 'NoneType' object has no attribute 'topk'
`

**Comment by dzf19927** [comment]
Is sth. wrong about the homura env?

**Comment by moskomule** [comment]
How about `pip install -U git+https://github.com/moskomule/homura@v0.7`?

**Comment by dzf19927** [comment]
> Sorry for typo in `github`.
> 
> How about `pip install -U git+https://github.com/moskomule/homura@v0.7`?
em...it is not for python, maybe C++，so strange.
`/home/dengzhifang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py:171: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
`

**Comment by moskomule** [comment]
Hi, now it should work.

**Comment by dzf19927** [comment]
ok, thank u very much

**Comment by 123chengbo** [comment]
@dzf19927 @moskomule when i use pip install -U git+https://github.com/moskomule/homura@v0.7, i got the same error

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

how did you solve this issue?
