### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by Hub-Tian** [moskomule/senet.pytorch#63]
With pytorch1.1, I meet the following errors.
Traceback (most recent call last):
  File "./imagenet.py", line 4, in <module>
    from homura.vision.data import imagenet_loaders
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/vision/__init__.py", line 1, in <module>
    from .data import *
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/vision/data/__init__.py", line 1, in <module>
    from .datasets import register_vision_dataset, VisionSet
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/vision/data/datasets.py", line 4, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by moskomule** [comment]
`dataclasses` is introduced in Python 3.7. Actually, the codebase in this repository is not compatible with the latest `homura`, so use `pip install -U git+https://github.com/moskomule/homura@v0.7`.

**Comment by Hub-Tian** [comment]
This error is gone after I use the homura@v0.7, however, I meet a new problem as follows:

Traceback (most recent call last):
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extensi
on_module
    check=True)
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./imagenet.py", line 2, in <module>
    from homura import optim, lr_scheduler, callbacks, reporters, init_distributed
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/__init__.py", line 3, in <module>
    from . import callbacks, debug, liblog, lr_scheduler, optim, reporters, trainers, metrics, modules, utils, vision
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/callbacks/__init__.py", line 3, in <module>
    from .metrics import AccuracyCallback, LossCallback, MetricCallback, metric_callback_decorator, IOUCallback
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/callbacks/metrics.py", line 8, in <module>
    from homura.metrics import confusion_matrix
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/metrics/__init__.py", line 2, in <module>
    from .segmentation import *
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/metrics/segmentation.py", line 5, in <module>
    from homura.modules import to_onehot
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/modules/__init__.py", line 3, in <module>
    from .discretization import *
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/modules/discretization.py", line 4, in <module>
    from .functional import (gumbel_sigmoid, straight_through_estimator,
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/modules/functional/__init__.py", line 6, in <module
>
    from .sinkhorn import sinkhorn
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/homura/modules/functional/sinkhorn.py", line 206, in <modu
le>
    extra_cuda_cflags=["--expt-relaxed-constexpr"])
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 773, in load_inline
    is_python_module)
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 866, in _write_ninja_f
ile_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extensi
on_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'wasserstein': b'[1/3] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=wasserstein -DTORCH_API_INCLUDE_EXTENSION_
H -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include -isystem /home/users/ABC/anacond
a3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1
.1/lib/python3.6/site-packages/torch/include/TH -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/inc
lude/THC -isystem /usr/local/cuda-9.2/include -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/include/python3.6m -D_GLIBCXX_USE_CXX11
_ABI=1 -fPIC -std=c++11 -c /tmp/torch_extensions/wasserstein/main.cpp -o main.o\n[2/3] /usr/local/cuda-9.2/bin/nvcc -DTORCH_EXTENSION_NAME=wasserstei
n -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include -isystem
/home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/users/yonglin.
tian/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include/TH -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/p
ython3.6/site-packages/torch/include/THC -isystem /usr/local/cuda-9.2/include -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/include
/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options \
'-fPIC\' --expt-relaxed-constexpr -std=c++11 -c /tmp/torch_extensions/wasserstein/cuda.cu -o cuda.cuda.o\nFAILED: cuda.cuda.o \n/usr/local/cuda-9.2/b
in/nvcc -DTORCH_EXTENSION_NAME=wasserstein -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python
3.6/site-packages/torch/include -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include/torch/csrc/
api/include -isystem /home/users/ABC/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include/TH -isystem /home/users/yonglin
.tian/anaconda3/envs/py3.6_torch1.1/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda-9.2/include -isystem /home/users/yonglin.t
ian/anaconda3/envs/py3.6_torch1.1/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_
NO_HALF2_OPERATORS__ --compiler-options \'-fPIC\' --expt-relaxed-constexpr -std=c++11 -c /tmp/torch_extensions/wasserstein/cuda.cu -o cuda.cuda.o\n/t
mp/torch_extensions/wasserstein/cuda.cu(157): error: identifier "TORCH_CHECK" is undefined\n\n1 error detected in the compilation of "/tmp/tmpxft_000
02e97_00000000-6_cuda.cpp1.ii".\nninja: build stopped: subcommand failed.\n'

Do you have any idea to solve it?  BTW, I use cuda9.2, pytorch1.1 and python3.6.

**Comment by moskomule** [comment]
I will check the problem in a couple of days.

**Comment by dadiaomengmeimei** [comment]
well I have the same problem, how to fix it

**Comment by muyue1238** [comment]
ran into the same problem, have you sovled it? @moskomule

**Comment by moskomule** [comment]
Hi, Python 3.6 has no `dataclasses` in its standard library. I will remove the dependencies.

**Comment by moskomule** [comment]
Hi, I updated this repository, so please check README.md and try it again.

**Comment by muyue1238** [comment]
The problem is gone now I believe.
