### ISSUE TITLE
about tensor size

### ISSUE THREAD

**Issue by Dtappledoghuati** [moskomule/senet.pytorch#64]
out += residual
RuntimeError: The expanded size of the tensor (15) must match the existing size (16) at non-singleton dimension 3

How should I solve this problem？

**Comment by moskomule** [comment]
Can you give me more details? Which line assets the error? What is your input?

**Comment by Dtappledoghuati** [comment]
> Can you give me more details? Which line assets the error? What is your input?

Traceback (most recent call last):
  File "../../tools/train.py", line 320, in <module>
    main()
  File "../../tools/train.py", line 315, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 213, in train
    outputs = model(data)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/misstian/tnq/pysot/tools/pysot/utils/distributed.py", line 43, in forward
    return self.module(*args, **kwargs)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/misstian/tnq/pysot/tools/pysot/models/model_builder.py", line 87, in forward
    zf = self.backbone(template)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/misstian/tnq/pysot/tools/pysot/models/backbone/resnet_atrous.py", line 219, in forward
    p2 = self.layer2(p1)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/misstian/tnq/pysot/tools/pysot/models/backbone/resnet_atrous.py", line 132, in forward
    out += residual
RuntimeError: The expanded size of the tensor (15) must match the existing size (16) at non-singleton dimension 3

in the out of Bottleneck

**Comment by moskomule** [comment]
I don't know what is `resnet_atrous.py`.

**Comment by Dtappledoghuati** [comment]
I'm sorry, I didn't make it clear. I put the se module into the target tracking backbone, and the result of the above dimensions did not match. Sorry, I just want to ask you if there is a solution.
