### ISSUE TITLE
RuntimeError: dataset DataSet(root, train, transform, download) is expected, but <class 'torchvision.datasets.cifar.CIFAR10'> has arguments of set() instead

### ISSUE THREAD

**Issue by JamesLee789** [moskomule/senet.pytorch#74]
After I set **download=True** in **line 11,cifar.py**, 

**line 11: train_loader, test_loader = DATASET_REGISTRY("cifar10")(args.batch_size, num_workers=args.num_workers,download=True)**

trying to download and prepare the CIFAR10 dataset, there came the errors as follows:

**$ python cifar.py** 

Traceback (most recent call last):
  File "cifar.py", line 3, in <module>
    from homura import callbacks, lr_scheduler, optim, reporters
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/__init__.py", line 8, in <module>
    Registry.import_modules('homura.vision')
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/register.py", line 97, in import_modules
    module = importlib.import_module(package_name)
  File "/home/lee/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/vision/__init__.py", line 2, in <module>
    from .data import DATASET_REGISTRY
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/vision/data/__init__.py", line 2, in <module>
    from .datasets import VisionSet, DATASET_REGISTRY
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/vision/data/datasets.py", line 230, in <module>
    {'cifar10': VisionSet(datasets.CIFAR10, "~/.torch/data/cifar10", 10,
  File "<string>", line 10, in __init__
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/vision/data/datasets.py", line 86, in __post_init__
    raise RuntimeError(f"dataset DataSet(root, train, transform, download) is expected, "
**RuntimeError: dataset DataSet(root, train, transform, download) is expected, but <class 'torchvision.datasets.cifar.CIFAR10'> has arguments of set() instead.**

How could I fix this problem? Many thanks for your help!

**Comment by moskomule** [comment]
Hi, I think it's because of the API change in the latest torchvision.
Check the latest homura's https://github.com/moskomule/homura/blob/cc48709cbdf894b91b40c304db71495c9523eab1/homura/vision/data/datasets.py#L105.

**Comment by JamesLee789** [comment]
Thank you very much! I downgraded my torchvision version to 0.7.0 and it worked!

However,when I trained the model,it got stuck in the following "RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable" error. What's wrong with the CUDA?


$ python cifar.py 
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /home/lee/.torch/data/cifar10/cifar-10-python.tar.gz
100%|███████████████████████████████████████▉| 170409984/170498071 [15:52<00:00, 612066.58it/s]Extracting /home/lee/.torch/data/cifar10/cifar-10-python.tar.gz to /home/lee/.torch/data/cifar10
Files already downloaded and verified
                                                                                Traceback (most recent call last):                                     | 0/200 [00:00<?, ?it/s]
  File "cifar.py", line 38, in <module>
    main()
  File "cifar.py", line 22, in main
    with Trainer(model, optimizer, F.cross_entropy, scheduler=scheduler, callbacks=_callbacks) as trainer:
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/trainers.py", line 519, in __init__
    super(SupervisedTrainer, self).__init__(model, optimizer, loss_f, callbacks=callbacks, scheduler=scheduler,
  File "/home/lee/anaconda3/lib/python3.8/site-packages/homura/trainers.py", line 98, in __init__
    self.model.to(self.device)
  File "/home/lee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 607, in to
    return self._apply(convert)
  File "/home/lee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/home/lee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/home/lee/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 605, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
**RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable**
170500096it [15:59, 177622.22it/s]                                                             
  0%|                                                   | 0/200 [00:03<?, ?it/s]

**Comment by moskomule** [comment]
I'm not sure about this... Check https://pytorch.org/get-started/previous-versions/.

**Comment by JamesLee789** [comment]
Maybe it's due to my GPUs' memory too low? What's your recommend hardware requirement during training and inference? Thanks!

**Comment by moskomule** [comment]
I don't think `cifar.py` consumes much memory (~2GB I guess). Try

* reboot your computer
* reinstall pytorch by following https://pytorch.org/get-started/previous-versions/
* reinstall cuda

**Comment by JamesLee789** [comment]
I will try it out.Thank you!
